#!/usr/bin/with-contenv bashio

set -e

# Get configuration
INFLUX_EVCC_DB=$(bashio::config 'influx_evcc_db')
INFLUX_EVCC_USER=$(bashio::config 'influx_evcc_user')
INFLUX_EVCC_PASSWORD=$(bashio::config 'influx_evcc_password')
INFLUX_AGGR_DB=$(bashio::config 'influx_aggr_db')
INFLUX_AGGR_USER=$(bashio::config 'influx_aggr_user')
INFLUX_AGGR_PASSWORD=$(bashio::config 'influx_aggr_password')
INFLUX_HOST=$(bashio::config 'influx_host')
INFLUX_PORT=$(bashio::config 'influx_port')
PEAK_POWER_LIMIT=$(bashio::config 'peak_power_limit')
HOME_BATTERY=$(bashio::config 'home_battery')
DYNAMIC_TARIFF=$(bashio::config 'dynamic_tariff')
TIMEZONE=$(bashio::config 'timezone')
ENERGY_SAMPLE_INTERVAL=$(bashio::config 'energy_sample_interval')
TARIFF_PRICE_INTERVAL=$(bashio::config 'tariff_price_interval')
CRON_YESTERDAY=$(bashio::config 'cron_yesterday')
CRON_TODAY=$(bashio::config 'cron_today')
DEBUG=$(bashio::config 'debug')

# Convert booleans
HOME_BATTERY_CONF=$([ "$HOME_BATTERY" = "true" ] && echo "true" || echo "false")
DYNAMIC_TARIFF_CONF=$([ "$DYNAMIC_TARIFF" = "true" ] && echo "true" || echo "false")
DEBUG_CONF=$([ "$DEBUG" = "true" ] && echo "true" || echo "false")

# Generate configuration file
bashio::log.info "Generating evcc-influx-aggregate.conf..."
cat > /app/scripts/evcc-influx-aggregate.conf << EOF
# Auto-generated by Home Assistant addon
INFLUX_EVCC_DB="${INFLUX_EVCC_DB}"
INFLUX_EVCC_USER="${INFLUX_EVCC_USER}"
INFLUX_EVCC_PASSWORD="${INFLUX_EVCC_PASSWORD}"
INFLUX_AGGR_DB="${INFLUX_AGGR_DB}"
INFLUX_AGGR_USER="${INFLUX_AGGR_USER}"
INFLUX_AGGR_PASSWORD="${INFLUX_AGGR_PASSWORD}"
INFLUX_HOST="${INFLUX_HOST}"
INFLUX_PORT=${INFLUX_PORT}
PEAK_POWER_LIMIT=${PEAK_POWER_LIMIT}
HOME_BATTERY="${HOME_BATTERY_CONF}"
DYNAMIC_TARIFF="${DYNAMIC_TARIFF_CONF}"
TIMEZONE="${TIMEZONE}"
ENERGY_SAMPLE_INTERVAL="${ENERGY_SAMPLE_INTERVAL}"
TARIFF_PRICE_INTERVAL="${TARIFF_PRICE_INTERVAL}"
DEBUG="${DEBUG_CONF}"
EOF

bashio::log.info "Starting EVCC Influx Aggregator..."
bashio::log.info "InfluxDB Host: ${INFLUX_HOST}:${INFLUX_PORT}"
bashio::log.info "EVCC DB: ${INFLUX_EVCC_DB}"
bashio::log.info "Aggregation DB: ${INFLUX_AGGR_DB}"
bashio::log.info "Timezone: ${TIMEZONE}"
bashio::log.info "Home Battery: ${HOME_BATTERY_CONF}"
bashio::log.info "Dynamic Tariff: ${DYNAMIC_TARIFF_CONF}"
bashio::log.info "Cron yesterday: ${CRON_YESTERDAY}"
bashio::log.info "Cron today: ${CRON_TODAY}"

# Run initial detection
bashio::log.info "Detecting vehicles and loadpoints..."
cd /app/scripts
./evcc-influx-aggregate.sh --detect 2>&1 || bashio::log.warning "Detection failed - will retry on next run"

# Check if a one-time command should be run
RUN_ONCE=$(bashio::config 'run_once')
if [ -n "$RUN_ONCE" ] && [ "$RUN_ONCE" != "null" ]; then
    bashio::log.info "Running one-time command: ./evcc-influx-aggregate.sh ${RUN_ONCE}"
    bashio::log.info "This may take a long time depending on the date range..."
    cd /app/scripts
    ./evcc-influx-aggregate.sh ${RUN_ONCE} 2>&1
    bashio::log.info "One-time command finished. Clear 'run_once' in the addon config to avoid re-running on next restart."
fi

# Generate crontab
cat > /tmp/crontab << CRON
${CRON_YESTERDAY} cd /app/scripts && ./evcc-influx-aggregate.sh --yesterday >> /var/log/evcc-aggregate.log 2>&1
${CRON_TODAY} cd /app/scripts && ./evcc-influx-aggregate.sh --today >> /var/log/evcc-aggregate.log 2>&1
CRON

bashio::log.info "Cron jobs configured. Aggregator is running."

# Create log file
touch /var/log/evcc-aggregate.log

# Run supercronic in foreground and tail the log
exec supercronic /tmp/crontab &
CRONIC_PID=$!

# Tail the log file so output appears in addon logs
tail -f /var/log/evcc-aggregate.log &
TAIL_PID=$!

# Wait for either process to exit
wait $CRONIC_PID $TAIL_PID
