name: "SONOS-Kids-Controller - Child 2"
description: "This software can be used to create a touch-based Sonos controller for your kids"
version: "1.0.1"
slug: "sonos_kids_controller_2"
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: services
ports:
  8200/tcp: 8200
webui: http://[HOST]:[PORT:8200]/
map:
  - type: config
    read_only: False
options:
  clientid: ""
  clientsecret: ""
  room: ""
  data: ""
  apiserver: "127.0.0.1"
  apiport: 5005
schema:
  clientid: str
  clientsecret: str
  room: str
  data: str
  apiserver: str
  apiport: int
configuration:
  clientid:
    name: Spotify ClientID
    description: Insert your Spotify Client ID
  clientsecret:
    name: Spotify Client Secret
    description: Insert your Spotify Client Secret
  room:
    name: Room
    description: Name of the room
  apiserver:
    name: SONOS API Server
    description: IP address of the SONOS API server
  apiport:
    name: SONOS API Port
    description: Port of the SONOS API server
  data:
    name: Data
    description: data file to send
