name: "SONOS API"
description: "Container based SONOS http api"
version: "1.0.18"
slug: "sonos_api"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
url: "hhttps://github.com/TMA84/ha-addons"
startup: services
init: false
options:
  settings: "192.168.178.74"
  presets: 502
  loglevel: "INFO"
schema:
  settings: str
  presets: str
  loglevel: list(INFO|DEBUG|ERROR)