name: "SONOS API"
description: "Container based SONOS http api"
version: "0.1"
slug: "sonos_api"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
url: "hhttps://github.com/TMA84/ha-addons"
startup: services
init: false
webui: http://[HOST]:[PORT:5005]/
options:
  settings: /config/settings.json
  presets: /config/presets
  loglevel: "INFO"
schema:
  settings: str
  presets: str
  loglevel: list(INFO|DEBUG|ERROR)
host_network: true
map:
  - type: addon_config
    read_only: false