build_from:
  aarch64: docker pull ghcr.io/hassio-addons/base-nodejs/arm64:stable
  amd64: docker pull ghcr.io/hassio-addons/base-nodejs/amd64:0416294
  armv7: docker pull ghcr.io/hassio-addons/base-nodejs/armv7:0416294